# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
BUILDDIR      = _build
SOURCEDIR     = .
OUTPUTDIR     = $(BUILDDIR)/html

# Internal variables.
ALLSPHINXOPTS   = -d $(BUILDDIR)/doctrees $(SPHINXOPTS) $(SOURCEDIR)

.PHONY: help clean html linkcheck save

default: html

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  html     : make standalone HTML files"
	@echo "  linkcheck: check all external links for integrity"
	@echo "  github   : upload the web site via ghp-import"

clean:
	-rm -rf $(BUILDDIR)/*
	-rm -f *~

html: clean
	$(SPHINXBUILD) -b html $(ALLSPHINXOPTS) $(BUILDDIR)/html
	@echo
	@echo "Build finished. The HTML pages are in $(BUILDDIR)/html."

linkcheck: site
	$(SPHINXBUILD) -b linkcheck $(ALLSPHINXOPTS) $(BUILDDIR)/linkcheck
	@echo
	@echo "Link check complete; look for any errors in the above output " \
	      "or in $(BUILDDIR)/linkcheck/output.txt."

save: clean html
	git add _build/html
	git commit -m "Generated by the website branch of the grave repository."
	@echo
	@echo "Push the website branch to GH when ready."
